### ISSUE TITLE
Getting Errors on mkdocs serve

### ISSUE THREAD

**Issue by a2liquidwms** [RetroPie/RetroPie-Docs#11]
I am trying to fork docs and contribute, but I'm getting errors when running mkdocs serve on this project.  I'm new to mkdocs, but looks like I need to install dependencies?  Is there a way to get this to auto-install?  

>$ mkdocs serve
> INFO    -  Building documentation... 
> ERROR   -  Config value: 'theme'. Error: Unrecognised theme name: 'material'. The available installed themes are: readthedocs, mkdocs 
> ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "mdx_truly_sane_lists". 
> ERROR   -  Config value: 'plugins'. Error: The "alternate-link" plugin is not installed 

I also tried to install the mkdocs-material project but get an error "Could not find a version that satisfies the requirement markdown>=3.2" when using pip install mkdocs-material. 

Any help? I'd love to contribute.

**Comment by a2ron44** [comment]
I figured this out and have a PR out there for install instructions on the README

**Comment by cmitu** [comment]
@a2liquidwms You don't need to install `mkdocs`, just edit the file in the repository (you can preview the output) and submit the modifications as a pull request. 
If you wish to install `mkdocs` locally, then you'll need to install some additional python3 dependencies - see how RetroPie build the [Docs](https://retropie.org.uk/docs/) from the wiki [here](https://github.com/RetroPie/RetroPie-Setup/blob/1d1d41520b92903591937ad4711ed2ea8de6d2ec/scriptmodules/admin/wikidocs.sh#L16).
