### ISSUE TITLE
Emulators are not showing after install and reboot 0 games still showing

### ISSUE THREAD

**Issue by lavexem** [RetroPie/RetroPie-Docs#21]
Hi everyone, 
I just bought a raspberry pi 4. Installed retro pie, followed all the instructions. But it still shows 0 games and no emulator seems to want to install. I have tried several times, but nothing seems to be working... 
Any idea why? I’m a bit lost... 
Thanks for your help :)

**Comment by cmitu** [comment]
Please use the forum for support or general questions. For your problem, see https://retropie.org.uk/docs/First-Installation/#emulationstation, you need to copy your games/roms to have any system show up.

**Comment by lavexem** [comment]
Shouldn’t there be already a few emulators installed by default? 
I see that when I run the install routine after connecting to the WiFi, it shows that emulators are being installed...

**Comment by joolswills** [comment]
Use the forum!
