### ISSUE TITLE
Commodore libretro docs outdated

### ISSUE THREAD

**Issue by sonninnos** [RetroPie/RetroPie-Docs#24]
Please update the Amiga and C64 libretro docs. A **lot** of things have changed since then.

https://github.com/libretro/libretro-uae/blob/master/README.md
https://github.com/libretro/vice-libretro/blob/master/README.md

Thanks!

**Comment by cmitu** [comment]
Well, thanks for making those changes ! We'll try to improve them.

**Comment by sonninnos** [comment]
I wrote proper docs in docs.libretro.com, feel free to take advantage:
https://docs.libretro.com/library/vice/
https://docs.libretro.com/library/puae/

**Comment by cmitu** [comment]
Amended to docs with #36 
* Amiga (P-UAE) - https://github.com/RetroPie/RetroPie-Docs/blob/51f4fe5b294eaa9e0d07a33fed7dc643a7e892d2/docs/Amiga.md
* Libretro Vice - https://github.com/RetroPie/RetroPie-Docs/blob/51f4fe5b294eaa9e0d07a33fed7dc643a7e892d2/docs/Commodore-64-VIC-20-PET.md (NB: currently we only include the `x64` core, but there's a PR to add a few more models).
