### ISSUE TITLE
Missing documentation/config for CEC support

### ISSUE THREAD

**Issue by donders** [RetroPie/RetroPie-Docs#31]
I was bothered by the seeming lack of CEC support for EmulationStation(ES) in RetroPie, as google only gave me a bodgy python script that piggybacked on a keyboard config in ES. By my own blundering I had to reinstall an RPI4 with retropie, thats when I came across [this PR](https://github.com/RetroPie/EmulationStation/pull/597). There is no mention of this ES feature in the setup script, nor any explanation on the docs website, apart from an ES changelog.

I have no CPP experience, but it seems that CEC support is only enabled if the `${CEC}` environment variable is set to "ON" while making/installing ES? I hope that means it is as simple as setting it in the terminal before starting the Retropie setup script. Does anyone know the recommended way to enable it? I'd be glad to write something up, but I don't even know for sure if CEC even works if I found out how to enable it.

edit: also, the solution with the python script breaks when combined with Kodi, I hope the "official" feature fares better, because there is no indication that Kodi's CEC implementation's intended behaviour should prevent other apps from using CEC, apart from a call to libcec's "destroy" function...

**Comment by cmitu** [comment]
This is the wrong repository to open this issue, but since you're here - AFAIK the CEC implementation in EmulationStation is not complete, hence the lack of any documentation or configuration option.

**Comment by donders** [comment]
Sorry about that. as I said, I didn't know if cec actually works. All I had to go on was the ES changelog which clearly indicates cec support is implemented, so I assumed the feature just wasnt part of the overarching retropie installation yet.
