### ISSUE TITLE
Proposed modification "First installation"

### ISSUE THREAD

**Issue by 51ckb01** [RetroPie/RetroPie-Docs#40]
Hello to all,
I think you could change the "First Installation" guide.
At this point [Here](https://github.com/RetroPie/RetroPie-Docs/blob/master/docs/First-Installation.md#extract)
It is proposed to extract the compressed file but, being that you propose to flash iso with **etcher**, this step can be skipped because the file **.gz** (for me **retropie-buster-4.7.1-rpi2_3.img.gz**) is decompressed by etcher itself (tested with version 1.5.108).

Thank you very much for all the work

**Comment by dankcushions** [comment]
what about the other listed imaging software? for example, `dd` won't do what you want if you give it a compressed file, as far as i remember. however if that's the only exception it could be noted as such, but we'd have to test all the software to make sure.

**Comment by 51ckb01** [comment]
Personally I have not tried `dd`

**Comment by cmitu** [comment]
This is not needed anymore, after the recent changes to the page.
