### ISSUE TITLE
Quasi88 not installable on the pi4

### ISSUE THREAD

**Issue by FollyMaddy** [RetroPie/RetroPie-Docs#42]
While checking the PC8800 docs.
Info of 2 emulators are shared of both quasi88(stand alone) and lr-quasi88.

To improve the docs I also had to install and check quasi88(stand alone).
But it was not listed, so I could not install.
For the pi4 at least, there is an issue in :
RetroPie-Setup/scriptmodules/emulators/quasi88.sh
When I change this line :
rp_module_flags="dispmanx !mali !kms"
Into :
rp_module_flags="dispmanx !mali"
Then I can install a working quasi88(stand alone).

I don't know why, but it would be nice if this could be fixed.

**Comment by cmitu** [comment]
The standalone emulator doesn't work well on the Pi4 - that's why is disabled on KMS platforms.

**Comment by FollyMaddy** [comment]
Thank you for explaining
