### ISSUE TITLE
Nintendo Switch Pro controller docs need updating

### ISSUE THREAD

**Issue by 877dev** [RetroPie/RetroPie-Docs#85]
Hi,

Thanks for the docs, I noticed a small update needed at https://retropie.org.uk/docs/Nintendo-Switch-Controllers/

Should be 3.2 like this, otherwise error "does not exist".
```
git clone https://github.com/nicman23/dkms-hid-nintendo
cd dkms-hid-nintendo
sudo dkms add .
sudo dkms build nintendo -v 3.2
sudo dkms install nintendo -v 3.2
```
Source https://github.com/nicman23/dkms-hid-nintendo

**Comment by cmitu** [comment]
Should be fixed now, thanks.
