### ISSUE TITLE
3DO BIOS md5 hash incorrect or filename incorrect

### ISSUE THREAD

**Issue by bnmoore** [RetroPie/RetroPie-Docs#91]
On the wiki page https://retropie.org.uk/docs/3do/, the md5 hash does not match the BIOS file. Is the hash incorrect? or is the BIOS actually panafz1.bin?

**Comment by cmitu** [comment]
Yes, the hash is from `panafz1.bin`, not from `panafz10.bin`. Will have to remedy that.
